(()=>{'use strict';const $=s=>document.querySelector(s),C=AllSpreads,key='kevbot-all-spreads-v1';let bundles={},all=[],saved={},busy=false;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),signed=n=>n==null?'Unavailable':(n>0?'+':'')+Number(n).toFixed(1),day=t=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Toronto',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(t));
 try{saved=JSON.parse(localStorage.getItem(key)||'{}');if(!saved||Array.isArray(saved)||typeof saved!=='object')saved={};}catch(_){}
 function persist(){try{localStorage.setItem(key,JSON.stringify(saved));$('#save-status').textContent='Selections saved in this browser.';return true;}catch(_){$('#save-status').textContent='Could not save. Export your selections before closing.';return false;}}
 function render(){all=Object.entries(bundles).flatMap(([s,b])=>C.rows(s,b));const from=$('#from').value,to=$('#through').value,league=$('#league').value;
 const visible=all.filter(r=>from&&to&&day(r.date)>=from&&day(r.date)<=to&&(league==='all'||r.sport===league));
 $('#games').innerHTML=visible.map(r=>{const selected=saved[r.key],side=selected?.side||r.side||'home',line=selected?.line??(r.line==null?'':side==='home'?r.line:-r.line),price=selected?.price??r.quote['spread_price_'+side]??'',book=selected?.book||r.quote.book||'';
 return `<article class="spread-row" data-key="${esc(r.key)}"><small>${esc(r.sport.toUpperCase())} · Week ${esc(r.week)} · ${esc(new Date(r.date).toLocaleString('en-CA',{timeZone:'America/Toronto'}))} ET</small><h2>${esc(r.away)} @ ${esc(r.home)}</h2><p>Model fair home spread: <b>${signed(r.mu==null?null:-r.mu)}</b> · Posted home spread: <b>${signed(r.line)}</b><br>Cover lean: <b>${r.side?esc(r[r.side]):r.gap===0?'No edge':r.mu==null?'Unavailable':'Needs a market line'}</b> · <b>${esc(r.rating)}</b></p><p>${esc(r.reason)}${r.projection_note?"<br>"+esc(r.projection_note):""}${r.quote.observed_at?"<br>Book quote observed: "+esc(r.quote.observed_at):""}</p><form><label>Your side<select name="side">${['away','home'].map(s=>`<option value="${s}" ${s===side?'selected':''}>${esc(r[s])}</option>`).join('')}</select></label><label>Chosen team spread<input name="line" type="number" step="0.5" required value="${esc(line)}"></label><label>American price<input name="price" type="number" step="1" required value="${esc(price)}"></label><label>Sportsbook<input name="book" required value="${esc(book)}"></label><button ${busy||r.locked?'disabled':''}>${r.locked?'Started / unavailable':selected?'Update selection':'Select spread'}</button></form></article>`;}).join('')||'<p>No games in this range. Choose another date or check the feed status.</p>';
 $('#saved').innerHTML=Object.values(saved).map(r=>`<p class="saved-row">${esc(r.source+' · '+r.event+' · '+r.pick+' ('+r.price+') · '+r.book+' · '+r.forecast_rating)} <button data-remove="${esc(r.key)}">Remove</button></p>`).join('')||'<p>No spreads selected.</p>';$('#ticket').disabled=$('#export').disabled=!Object.keys(saved).length;
 }
 $('#games').addEventListener('change',e=>{if(e.target.name!=='side')return;const article=e.target.closest('[data-key]'),r=all.find(r=>r.key===article.dataset.key),form=e.target.form;if(r?.line!=null)form.line.value=e.target.value==='home'?r.line:-r.line;form.price.value=r?.quote['spread_price_'+e.target.value]??'';});
 $('#games').addEventListener('submit',e=>{e.preventDefault();const f=e.target,r=all.find(r=>r.key===f.closest('[data-key]').dataset.key),s=r&&C.selection(r,f.side.value,f.line.value,f.price.value,f.book.value);if(!s){$('#save-status').textContent='Use an upcoming game, valid spread, American price of at least ±100 and named book.';return;}saved[s.key]=s;persist();render();});
 $('#saved').addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(b){delete saved[b.dataset.remove];persist();render();}});
 const download=(blob,name)=>{const a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
 $('#export').onclick=()=>download(new Blob([JSON.stringify({schema:1,manual_selections:true,selections:Object.values(saved)},null,2)],{type:'application/json'}),'kevbot-spread-selections.json');
 $('#ticket').onclick=async()=>{try{await MoneylineCard.drawTicket($('#ticket-canvas'),{day:day(Date.now()),id:'manual-spreads',picks:Object.values(saved)},{style:'slip',override:{title:'MY SPREADS',subtitle:'MANUAL SELECTIONS · VERIFY BOOK PRICES',stats:[['PICKS',String(Object.keys(saved).length)],['TYPE','MANUAL'],['STAKES','UNSET'],['STATUS','PLAN']],legal:'Manual bet plan · No wagers placed · Verify exact lines and prices at your book'}});$('#ticket-dialog').showModal();}catch(_){$('#save-status').textContent='Could not draw ticket. Export your selections.';}};
 $('#close').onclick=()=>$('#ticket-dialog').close();$('#download').onclick=()=>$('#ticket-canvas').toBlob(b=>b&&download(b,'kevbot-spreads.png'));
 async function refresh(){busy=true;$('#refresh').disabled=true;render();const results=await Promise.all(['nfl','ncaaf'].map(async sport=>{const names=sport==='nfl'?['meta','games','board','games_detail','outlook']:['meta','games','board'];try{const values=await Promise.all(names.map(async name=>{const r=await fetch('../'+sport+'-edge-lab/data/'+name+'.json',{cache:'no-store',signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error();return r.json();}));return [sport,Object.fromEntries(names.map((n,i)=>[n==='games_detail'?'details':n,values[i]]))];}catch(_){return [sport,null];}}));bundles=Object.fromEntries(results.filter(x=>x[1]));busy=false;$('#refresh').disabled=false;$('#status').textContent=results.map(([s,b])=>s.toUpperCase()+': '+(b?b.games.length+' scheduled games · forecasts '+b.meta.generated_at:'feed unavailable')).join(' · ');render();}
 const params=new URLSearchParams(location.search);$('#from').value=/^\d{4}-\d{2}-\d{2}$/.test(params.get('from')||'')?params.get('from'):day(Date.now());$('#through').value=/^\d{4}-\d{2}-\d{2}$/.test(params.get('through')||'')?params.get('through'):day(Date.now()+6*86400000);if(['nfl','ncaaf'].includes(params.get('league')))$('#league').value=params.get('league');for(const id of ['from','through','league'])$('#'+id).onchange=render;$('#refresh').onclick=refresh;setInterval(render,30000);window.addEventListener('message',e=>{if(e.origin===location.origin&&e.data?.type==='kevbotbets:activate'&&!busy)refresh();});refresh();
})();
