(()=>{'use strict';
const $=s=>document.querySelector(s),T=window.KevTickets,R=window.KevTicketRenderer,Store=window.KevTicketStore;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=v=>v==null?'—':(v*100).toFixed(1)+'%',odds=v=>v==null?'—':(v>0?'+':'')+v;
let local=Store.list(),sharedIds=new Set(),choices=[];
let index={tickets:[]},results={entries:{}},current=null,blob=null,url='',version=0;
async function get(file){const r=await fetch('data/tickets/'+file,{cache:'no-store',signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error('Archive data unavailable');return r.json();}
function download(value,name,type){const link=document.createElement('a'),u=URL.createObjectURL(value instanceof Blob?value:new Blob([value],{type}));link.href=u;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(u),2000);}
function report(){const entries=Object.values(results.entries||{}),groups=T.performance(entries,$('#performance-group').value);$('#archive-performance').innerHTML=groups.length?'<div class="table-scroll"><table><thead><tr><th>Group</th><th>W–L–P</th><th>Pending / Void</th><th>Net units</th><th>ROI</th><th>Probability error</th></tr></thead><tbody>'+groups.map(g=>'<tr><td>'+esc(g.label)+'</td><td>'+g.wins+'–'+g.losses+'–'+g.pushes+'</td><td>'+g.pending+' / '+g.voids+'</td><td>'+g.units.toFixed(2)+'</td><td>'+pct(g.roi)+'</td><td>'+(g.brier==null?'Collecting':g.brier.toFixed(3))+' · n='+g.probabilityN+'</td></tr>').join('')+'</tbody></table></div>':'<p>No published results yet. A record will build as archived picks settle.</p>';}
function detail(){if(!current)return;$('#archive-detail').innerHTML='<h2>'+esc(current.day)+' · '+current.picks.length+' picks</h2><p class="note">Published '+esc(current.published_at)+' · '+esc(current.ranking||'')+'</p><div class="table-scroll"><table><thead><tr><th>Pick</th><th>Original odds</th><th>Result</th><th>Last quote before start</th></tr></thead><tbody>'+current.picks.map(r=>{const e=results.entries[T.outcomeKey(r)]||{},c=e.closing;
return '<tr><td>'+esc(r.pick)+'<br><small>'+esc(r.event)+' · '+esc(r.book)+'</small></td><td>'+odds(r.price)+(r.line!=null?' · line '+esc(r.line):'')+'</td><td>'+esc(e.result?.status||'Pending')+(e.result?.source?' <a href="'+esc(e.result.source)+'" target="_blank" rel="noopener">Source</a>':'')+(e.review?'<br><small>'+esc(e.review)+'</small>':'')+'</td><td>'+(c?odds(c.price)+(c.line!=null?' · line '+esc(c.line):'')+'<br><small>'+esc(c.minutes_before_start)+' min before start · '+esc(c.book)+(c.line_advantage!=null?' · line advantage '+c.line_advantage:'')+(c.price_advantage!=null?' · implied price difference '+pct(c.price_advantage):' · price difference unavailable across different lines')+'</small>':'Not captured')+'</td></tr>';}).join('')+'</tbody></table></div><p class="note">The last observed quote is a closing proxy, not a guaranteed closing price. Positive line advantage means the original line was more favorable for that selection.</p>';}
async function preview(){if(!current)return;const v=++version;$('#archive-image').disabled=true;try{const canvas=document.createElement('canvas');await R.draw(canvas,current,{style:$('#archive-style').value,results:$('#archive-results').checked?results.entries:null});const b=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(v!==version)return;blob=b;if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(blob);$('#archive-preview').src=url;$('#archive-preview').hidden=false;$('#archive-image').disabled=false;}catch(e){$('#archive-status').textContent=e.message;}}
async function select(){const value=$('#archive-select').value,ticket=choices.find(t=>t.id===value);if(!ticket)return;try{const chosen=ticket.local?local.find(t=>t.id===ticket.id):await get(ticket.path);if($('#archive-select').value!==value)return;current=chosen;detail();$('#archive-json').disabled=false;await preview();}catch(e){$('#archive-status').textContent=e.message;}}
function refreshChoices(){const selected=$('#archive-select').value;choices=[...local.map(t=>({id:t.id,day:t.day,published_at:t.published_at,count:t.picks.length,local:true})),...index.tickets];$('#archive-select').innerHTML=choices.map(t=>'<option value="'+esc(t.id)+'">'+esc(t.day+' · '+t.published_at.slice(11,16)+' UTC · '+t.count+' picks'+(t.local?(sharedIds.has(t.id)?' · sheet backup':' · this browser'):' · public'))+'</option>').join('');if(choices.some(t=>t.id===selected))$('#archive-select').value=selected;}
async function backup(){const button=$('#backup-tickets');if(button.disabled)return;button.disabled=true;$('#backup-status').textContent='Syncing original picks…';try{const result=await Store.sync();local=result.tickets;sharedIds=new Set(result.sharedIds||[]);$('#backup-status').textContent=result.message;refreshChoices();if(!current)await select();}catch(e){$('#backup-status').textContent='Ticket backup failed. Local originals are retained; check your Ledger connection and retry.';}finally{button.disabled=false;}}
$('#archive-style').innerHTML=Object.entries(R.styles).map(([v,label])=>'<option value="'+v+'">'+label+'</option>').join('');
$('#archive-select').onchange=select;$('#archive-style').onchange=preview;$('#archive-results').onchange=preview;$('#performance-group').onchange=report;
$('#backup-tickets').onclick=backup;
window.addEventListener('online',backup);
window.addEventListener('storage',event=>{if(event.key==='kevbot.local-tickets.v1'){local=Store.list();refreshChoices();}});
window.addEventListener('message',event=>{if(event.source===window.parent&&event.origin===location.origin&&event.data?.type==='kevbotbets:activate'){local=Store.list();refreshChoices();backup();}});
$('#archive-image').onclick=()=>blob&&download(blob,'kevbot-bets-top-picks-'+current.day+'-'+current.id+($('#archive-results').checked?'-results':'')+'.png');
$('#archive-json').onclick=()=>current&&download(JSON.stringify(current,null,2),'kevbot-ticket-'+current.id+'.json','application/json');
(async()=>{try{const all=await Promise.allSettled([get('index.json'),get('results.json'),get('health.json')]);index=all[0].status==='fulfilled'?all[0].value:{tickets:[]};results=all[1].status==='fulfilled'?all[1].value:{entries:{}};const health=all[2].status==='fulfilled'?all[2].value:{feeds:{}};
$('#archive-status').textContent=all.every(r=>r.status==='fulfilled')?(index.tickets.length+' public snapshots · Archive checked '+(index.checked_at||'not yet')+'.'):'Public archive unavailable. Local originals remain available; unknown results stay Pending.';
refreshChoices();
$('#archive-health').innerHTML=Object.entries(health.feeds||{}).map(([k,h])=>'<article class="card"><h3>'+esc(k.toUpperCase())+'</h3><span class="tag '+esc(h.status)+'">'+esc(h.status)+'</span><p>Published '+esc(h.published_at||'unknown')+'</p><p class="note">Last successful read '+esc(h.last_good_at||'none')+'</p>'+(h.failed_fields.length?'<p class="warning">Failed: '+esc(h.failed_fields.join(', '))+'</p>':'')+(h.warnings||[]).map(w=>'<p class="warning">'+esc(w)+'</p>').join('')+'</article>').join('')+(health.result_failures?.length?'<p class="warning">'+health.result_failures.length+' result feed(s) failed; previous verified results retained.</p>':'');report();await select();
}catch(e){$('#archive-status').textContent='Public archive unavailable. Local originals remain available.';refreshChoices();await select();}finally{backup();}})();
})();
