(() => {
  'use strict';
  const $=s=>document.querySelector(s), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const pct=x=>Number.isFinite(x)?(100*x).toFixed(1)+'%':'—', num=(x,n=1)=>Number.isFinite(x)?x.toFixed(n):'—', signed=x=>Number.isFinite(x)?(x>0?'+':'')+x.toFixed(1):'—';
  const date=x=>{const d=new Date(x);return Number.isNaN(+d)?'Unknown time':d.toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'});};
  const price=x=>Number.isFinite(x)?(x>0?'+':'')+x:'—', names={current:'Current model',efficiency:'Play efficiency',market:'De-vigged market','lineup-context':'NHL context',ensemble:'Learned ensemble'};
  let data,tab=['competition','efficiency','lineups','prices','props','validation','calibration','weather','health'].includes(new URLSearchParams(location.search).get('tab'))?new URLSearchParams(location.search).get('tab'):'competition',limit=36,selected=new Set();
  const filters=()=>({sport:$('#lab-sport').value,book:$('#lab-book').value,search:$('#lab-search').value.toLowerCase().trim()});
  function match(r){const f=filters();return (f.sport==='all'||r.sport===f.sport)&&(f.book==='all'||r.book===f.book||(r.quotes||[]).some(q=>q.book===f.book))&&(!f.search||[r.matchup,r.player,r.team].filter(Boolean).join(' ').toLowerCase().includes(f.search));}
  function gameMatch(r){const f=filters();return (f.sport==='all'||r.sport===f.sport)&&(!f.search||[r.matchup,r.home_name,r.away_name].filter(Boolean).join(' ').toLowerCase().includes(f.search));}
  const tag=x=>`<span class="lab-tag">${esc(x)}</span>`, empty=x=>`<div class="lab-empty">${esc(x)}</div>`;
  const title=(eyebrow,h,p)=>`<div class="lab-intro"><p class="eyebrow">${esc(eyebrow)}</p><h2>${esc(h)}</h2><p>${esc(p)}</p></div>`;
  const more=count=>count>limit?'<button class="lab-more" id="lab-more">Show more records ↓</button>':'';
  function gameCard(g,body){return `<article class="lab-card"><div class="lab-card-top">${tag(g.sport+(g.season_type===1?' / preseason':''))}<span class="lab-date">${esc(date(g.start))}</span></div><h3>${esc(g.matchup)}</h3>${body}</article>`;}
  function competition(){
    const f=filters(),rows=data.lab.models.filter(r=>f.sport==='all'||r.sport===f.sport),games=data.games.filter(gameMatch);
    return title('PROSPECTIVE / SAME GAMES','Make every model prove it.','A new input earns its place by improving frozen forecasts on the same events. Lower Brier score and log loss are better. The archive starts prospectively; pending games are not wins.')+
      `<div class="lab-scroll"><table class="lab-table"><thead><tr><th>Model / league</th><th>Settled games</th><th>Brier ↓</th><th>Log loss ↓</th><th>Margin MAE ↓</th><th>ATS W–L–P</th><th>Quoted ROI</th><th>Paired evidence</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(names[r.model]||r.model)}<small>${esc(r.sport.toUpperCase())} / ${esc(r.cohort||'regular season')}<br>${esc(r.version||'')}</small></td><td>${r.games}</td><td>${num(r.brier,3)}</td><td>${num(r.log_loss,3)}</td><td>${num(r.margin_mae)}</td><td>${r.ats?`${r.ats.win}–${r.ats.loss}–${r.ats.push}`:'—'}</td><td>${pct(r.roi)}<small>${r.priced_games||0} priced games</small></td><td>${esc(r.model==='current'?'Baseline':r.comparison.status)}<small>vs current: ${r.comparison.games} paired games / ${r.comparison.days||0} dates${r.comparison.interval?' / Δ Brier CI '+r.comparison.interval.map(x=>num(x,3)).join(' to '):''}<br>vs market: ${r.market_comparison?.games||0} paired games · ${esc(r.market_comparison?.status||'Awaiting evidence')}</small></td></tr>`).join('')}</tbody></table></div>`+
      (data.lab.settled_events?`<div class="lab-grid">${rows.filter(r=>r.calibration.length).map(r=>`<article class="lab-card"><h3>${esc(names[r.model])} / ${esc(r.sport.toUpperCase())}</h3><p class="lab-subtle">Calibration: compare forecast probability with the observed win share.</p><table><thead><tr><th>Probability band</th><th>Games</th><th>Forecast</th><th>Observed</th></tr></thead><tbody>${r.calibration.map(b=>`<tr><td>${pct(b.low)}–${pct(b.high)}</td><td>${b.games}</td><td>${pct(b.forecast)}</td><td>${pct(b.actual)}</td></tr>`).join('')}</tbody></table></article>`).join('')}</div>`:empty('Awaiting settled prospective games. No accuracy gain has been established.'))+
      '<h2 style="margin-top:36px">The next comparisons</h2><div class="lab-grid">'+games.slice(0,limit).map(g=>gameCard(g,`<table><thead><tr><th>Model</th><th>Home win</th><th>Home margin</th></tr></thead><tbody>${g.models.map(m=>`<tr><td>${esc(names[m.model]||m.model)}</td><td>${pct(m.p_home)}</td><td>${signed(m.margin)}</td></tr>`).join('')}</tbody></table>${g.models.length?'<p class="lab-subtle">Positive margin = home team ahead. Experiments remain in shadow mode.</p>':'<p>No fresh forecast available.</p>'}`)).join('')+'</div>'+more(games.length);
  }
  function efficiency(){
    const games=data.games.filter(gameMatch).filter(g=>g.models.some(m=>m.model==='efficiency'));
    const c=data.coverage.nfl;
    return title('PLAY DATA / OPPONENT ADJUSTMENT','Look beneath the final score.','The NFL challenger separates passing and rushing efficiency, success, explosive plays, pace and home field. Ratings use prior dates only, shrink small samples and adjust for the opponents faced.')+
      `<div class="lab-comparison">${c.team_games} team-game inputs · ${c.efficiency_training_games} fitted games · ${c.residual_games} chronological residuals. Input observed ${esc(date(c.observed_at))}. Historical replay uses corrected public files and remains exploratory. NCAAF EPA data is not present.</div>`+
      '<div class="lab-grid">'+games.slice(0,limit).map(g=>{const m=g.models.find(x=>x.model==='efficiency'),current=g.models.find(x=>x.model==='current');return gameCard(g,`<div class="lab-forecast"><div><b>${signed(m.margin)}</b><small>HOME MARGIN<br>80% outcome range: ${signed(m.low)} to ${signed(m.high)}</small></div><div><b>${pct(m.p_home)}</b><small>HOME WIN<br>${m.cover?'Cover '+pct(m.cover.win)+' / push '+pct(m.cover.push):'No matched spread'}</small></div></div><div class="lab-factors">${m.factors.map(x=>`<div class="lab-factor ${x.points<0?'negative':''}"><span>${esc(x.name)}</span><div><i style="width:${Math.min(100,Math.abs(x.points)*12)}%"></i></div><b>${signed(x.points)}</b></div>`).join('')}</div><p class="lab-subtle">Contributions to fitted mean. Residual mixture shapes the outcome range.</p><div class="lab-comparison">Current-season games ${m.profiles?.home?.current_season_games??'—'} home / ${m.profiles?.away?.current_season_games??'—'} away. Data weight ${pct(m.profiles?.home?.efficiency_data_weight)} / ${pct(m.profiles?.away?.efficiency_data_weight)}; prior season weight 35%.<br>Current margin ${signed(current?.margin)} · challenger disagreement ${signed(current?m.margin-current.margin:null)} points. Large disagreement calls for review.</div>`);}).join('')+'</div>'+(games.length?more(games.length):empty('No eligible efficiency forecasts for this filter. Missing data produces no prediction.'));
  }
  function lineups(){
    const games=data.games.filter(gameMatch);
    return title('AVAILABILITY / CONDITIONAL FORECASTS','What changes if the lineup changes?','Inspect sensitivity around the existing forecast. Questionable-player scenarios have no invented participation weights. Unconfirmed goalies remain visible as missing evidence.')+
      '<div class="lab-grid">'+games.slice(0,limit).map(g=>gameCard(g,`<div class="lab-comparison">${(g.availability?.sides||[]).map(s=>`${esc(s.team)}: ${esc(s.starter||'Expected starter unavailable')} · ${esc(s.role_status)}<br>Absent ${s.absent.length} · questionable ${s.questionable.length} · offensive-line flags ${s.offensive_line_flags.length}`).join('<br>')}<br>Availability confidence multiplier ${num(g.availability?.confidence_multiplier,2)} · challenger only</div>`+(g.scenarios.length?`<label class="lab-subtle">Scenario<select class="lab-scenario-select" data-event="${esc(g.event_id)}" data-sport="${esc(g.sport)}" style="display:block;width:100%;margin-top:10px">${g.scenarios.map((s,i)=>`<option value="${i}">${esc(s.label)}</option>`).join('')}</select></label><div class="lab-scenario" id="scenario-${esc(g.sport)}-${esc(g.event_id)}">${scenarioBody(g.scenarios[0])}</div>`:'<p>No verified lineup adjustment is supplied. The model abstains from a replacement-value estimate.</p>'))).join('')+'</div>'+more(games.length);
  }
  function scenarioBody(s){return `<strong>${signed(s.margin)}</strong><span class="lab-subtle"> home margin${Number.isFinite(s.total)?' / total '+num(s.total):''}</span><p>${esc(s.reason||'Published forecast already includes its recorded context adjustments.')}</p><p>${esc((s.changes||[]).join(' · '))}${s.kind==='sensitivity'?' · Sensitivity only; no extra production injury adjustment.':''}</p>`;}
  function prices(){
    const rows=data.market.groups.map(g=>({...g,sport:g.contract[0],market:g.contract[2],player:g.quotes[0]?.player})).filter(match);
    return title('EXACT CONTRACT / ORIGINAL TIMESTAMPS','A good forecast needs a real price.','Compare identical lines and settlement rules. Different lines stay separate. A fair market probability requires both opposite prices at the same book and observation time.')+
      `<div class="lab-comparison">${data.market.accepted} accepted quote observations · ${data.market.rejected} rejected or unsupported observations. Freshness gate: pregame quotes observed within 12 hours. ${data.closing_prices.length} archived last-pregame-price comparisons; these are not guaranteed final closing lines.</div>`+
      `<div class="lab-scroll"><table class="lab-table"><thead><tr><th>Game / contract</th><th>Best same-line prices</th><th>Books</th><th>De-vigged probability</th><th>Same-book price history</th><th>Observed</th></tr></thead><tbody>${rows.slice(0,limit).map(g=>`<tr><td>${esc(g.matchup)}<small>${esc(g.sport.toUpperCase())} / ${esc(g.player||'')} ${esc(g.market)} ${g.contract[4]??''} · ${esc(g.contract[5])}</small></td><td>${Object.entries(g.best).filter(([,q])=>filters().book==='all'||q.book===filters().book).map(([side,q])=>`${esc(side)} ${price(q.price)}<small>${esc(q.book)} / decimal ${num(q.decimal,3)}</small>`).join('<br>')}</td><td>${g.books}<small>${esc(g.coverage)}</small></td><td>${g.devig_pairs.length?g.devig_pairs.map(p=>Object.entries(p.probabilities).map(([s,v])=>`${esc(s)} ${pct(v)}`).join(' / ')+`<small>${esc(p.book)} / overround ${pct(p.overround)}</small>`).join('<br>'):'—<small>Opposite quote unavailable</small>'}</td><td>${g.first&&g.latest?`${esc(g.first.side)} ${price(g.first.price)} → ${price(g.latest.price)}<small>${esc(g.first.book)} · identical line</small>`:'—'}</td><td>${esc(date(g.quotes[0]?.observed_at))}</td></tr>`).join('')}</tbody></table></div>`+more(rows.length)+(rows.length?'':empty('No fresh exact-contract quotes match this filter.'))+movementTable();
  }
  function movementTable(){
    const rows=(data.market.movements||[]).filter(match);
    return '<h2 style="margin-top:36px">Line movement, separately</h2><p>These observations may have different lines. Point movement stays separate from the exact-line price comparison above.</p>'+(rows.length?`<div class="lab-scroll"><table class="lab-table"><thead><tr><th>Game / market</th><th>Book / side</th><th>First line → latest</th><th>First price → latest</th><th>Original observations</th></tr></thead><tbody>${rows.slice(0,limit).map(r=>`<tr><td>${esc(r.matchup)}<small>${esc(r.market)} ${esc(r.player||'')}</small></td><td>${esc(r.book)}<small>${esc(r.side)}</small></td><td>${r.first_line??'—'} → ${r.latest_line??'—'}<small>Point change ${signed(r.line_change)}</small></td><td>${price(r.first_price)} → ${price(r.latest_price)}</td><td>${esc(date(r.first_at))}<small>${esc(date(r.latest_at))}</small></td></tr>`).join('')}</tbody></table></div>`:empty('Line movement needs a second observation at the same book. No opening line is invented.'));
  }
  function propEvidence(){
    const rows=(data.prop_lab?.models||[]).filter(r=>filters().sport==='all'||filters().sport===r.sport);
    return '<h2 style="margin-top:36px">Frozen prop comparisons</h2><p>Exact-line contracts, with one original price per contract. Pushes stay outside no-push Brier and log loss. Missing participation remains ungraded. Multiple books do not create extra samples.</p>'+(rows.length?`<div class="lab-scroll"><table class="lab-table"><thead><tr><th>Model</th><th>Contracts / games</th><th>Settled / pending</th><th>W–L–Push</th><th>Brier ↓</th><th>Log loss ↓</th><th>Quoted ROI</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.model==='opportunity'?'Opportunity challenger':'Current prop model')}<small>${esc(r.version)}</small></td><td>${r.contracts} / ${r.events}</td><td>${r.settled} / ${r.pending}</td><td>${r.wins}–${r.losses}–${r.pushes}</td><td>${num(r.brier,3)}</td><td>${num(r.log_loss,3)}</td><td>${pct(r.roi)}</td></tr>`).join('')}</tbody></table></div>`:empty('No frozen opportunity forecasts for this league.'));
  }
  function props(){
    const rows=data.props.filter(match),tickets=data.tickets.filter(t=>match({...t,sport:'nfl',player:t.legs.map(l=>l.player).join(' ')}));
    return title('OPPORTUNITIES / SHARED GAME OUTCOMES','Volume first. Correlation included.','NFL rushing attempts and targets are allocated from simulated team opportunities. Receptions depend on targets; receiving yards contribute to quarterback passing yards. Shared pace and game script connect related legs. These probabilities remain unvalidated.')+
      `<div class="lab-manual"><h3>Your simulation ticket</h3><p>Select 2–8 NFL legs below from one book. Same-game legs use shared draws. Distinct games are treated as independent.</p><output id="lab-ticket-result" aria-live="polite">Select legs to compare joint and independent probabilities.</output><button id="lab-clear">Clear selection</button></div>`+
      `<div class="lab-scroll"><table class="lab-table"><thead><tr><th>Select / player</th><th>Market / line</th><th>Opportunity forecast</th><th>Research win</th><th>Offered price</th><th>Model status</th></tr></thead><tbody>${rows.slice(0,limit).map(q=>`<tr><td><label><input class="lab-leg" type="checkbox" data-id="${esc(q.id)}" ${selected.has(q.id)?'checked':''}> ${esc(q.player)}</label><small>${esc(q.matchup)}</small></td><td>${esc(q.side)} ${q.line}<small>${esc(q.market)}</small></td><td>${num(q.probability.mean)}<small>80% outcome range ${num(q.probability.low)}–${num(q.probability.high)}</small></td><td>${pct(q.probability.win)}<small>Push ${pct(q.probability.push)}</small></td><td>${price(q.price)}<small>${esc(q.book)} / break-even ${pct(q.breakeven)}</small></td><td>Shadow research<small>${q.simulations.toLocaleString()} joint draws · participation conditional</small></td></tr>`).join('')}</tbody></table></div>`+more(rows.length)+workloadTable()+propEvidence()+(rows.length?'':empty('No eligible opportunity projections match this filter. NHL ice-time and NCAAF game-level workloads have not been imported, so their opportunity models abstain.'))+
      '<h2 style="margin-top:40px">Core & Longshot experiments</h2><p>Example selections rank raw simulation value at the observed book. They are research scenarios, with no quoted combined payout or ticket EV.</p><div class="lab-grid">'+tickets.map(t=>`<article class="lab-card lab-ticket"><div class="lab-card-top">${tag(t.profile+' / '+t.legs.length+' legs')}<span class="lab-date">${esc(t.book)}</span></div><div class="lab-forecast"><div><b>${pct(t.win)}</b><small>JOINT SIMULATION</small></div><div><b>${pct(t.independent_comparison)}</b><small>INDEPENDENT COMPARISON</small></div></div><ol>${t.legs.map(l=>`<li>${esc(l.player)}<small>${esc(l.side)} ${l.line} ${esc(l.market)} / ${price(l.price)}</small></li>`).join('')}</ol><p class="lab-subtle">${t.games} games · ${t.simulations.toLocaleString()} draws per game. Combined sportsbook price unavailable; EV unavailable.</p></article>`).join('')+'</div><h3 style="margin-top:32px">Coverage beyond NFL</h3><div class="lab-grid">'+['nhl','ncaaf'].map(s=>`<article class="lab-card">${tag(s)}<p>${data.coverage[s].history_rows} descriptive history rows / ${data.coverage[s].quotes} observed offers.</p><p>${esc(data.coverage[s].opportunity_status)}</p></article>`).join('')+'</div>';
  }
  function workloadTable(){
    const rows=(data.workloads||[]).filter(r=>r.expected_targets!=null&&match({...r,sport:'nfl'}));
    return '<h2 style="margin-top:32px">Workload before yards</h2><p>Snaps are estimated from simulated pass/rush opportunities and recent recorded snap share. Routes and gameday availability remain unknown.</p>'+`<div class="lab-scroll"><table class="lab-table"><thead><tr><th>Player</th><th>Recorded snap share</th><th>Expected snaps</th><th>Targets / carries</th><th>Availability confidence</th></tr></thead><tbody>${rows.slice(0,limit).map(r=>`<tr><td>${esc(r.player)}<small>${esc(r.team)} / ${r.samples} games</small></td><td>${pct(r.snap_share)}<small>${r.snap_samples} snap samples</small></td><td>${num(r.expected_snaps)}</td><td>${num(r.expected_targets)} / ${num(r.expected_carries)}<small>${esc(r.workload_note)}</small></td><td>${num(r.confidence_multiplier,2)}<small>Conditional on participation</small></td></tr>`).join('')}</tbody></table></div>`;
  }
  function validation(){
    return title('TEN IMPLEMENTED UPGRADES','Built to be measured.','Collection and comparison tools are active. A model earns production use through frozen future results; implementation alone does not establish better accuracy.')+'<div class="lab-grid">'+(data.upgrades||[]).map(u=>`<article class="lab-card"><div class="lab-card-top">${tag(String(u.id).padStart(2,'0'))}${tag(u.status)}</div><h3>${esc(u.name)}</h3><p>${esc(u.detail)}</p></article>`).join('')+'</div>';
  }
  function calibration(){
    const rows=(data.market_calibration?.markets||[]).filter(r=>filters().sport==='all'||r.sport===filters().sport);
    return title('SEPARATE MARKETS / EARLIER RESULTS ONLY','Calibrate the probability you actually use.','Moneyline, spreads, totals and each player market train separately. The fixed symmetric slope grid preserves complementary outcomes. Pushes stay outside conditional win/loss scoring.')+`<p>${esc(data.market_calibration?.policy||'No captures yet.')}</p><div class="lab-scroll"><table class="lab-table"><thead><tr><th>League / market</th><th>Captured / graded</th><th>Games / dates</th><th>Raw log loss ↓</th><th>Calibrated loss ↓</th><th>Next slope fit</th><th>Prospective review</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.sport.toUpperCase())} / ${esc(r.market)}<small>${esc(r.baseline_version)}</small></td><td>${r.captured} / ${r.graded}</td><td>${r.games} / ${r.dates}</td><td>${num(r.raw_log_loss,3)}</td><td>${num(r.calibrated_log_loss,3)}</td><td>${r.next_fit.enabled?num(r.next_fit.slope,2):'Not fitted'}<small>${esc(r.next_fit.reason)}</small></td><td>${esc(r.status)}<small>${r.interval?'Paired loss interval '+r.interval.map(x=>num(x,3)).join(' to '):'Needs more prospective dates'} · promotion disabled</small></td></tr>`).join('')}</tbody></table></div>`+(rows.length?'':empty('No fresh exact-price captures in this market yet.'));
  }
  function weather(){
    const rows=(data.weather||[]).filter(gameMatch);
    return title('KICKOFF HOUR / ROOF ASSUMPTIONS','Weather with a timestamp.','Review wind, gusts, rain and roof status together. Forecast hours more than an hour from kickoff are rejected; an unknown gust or roof state stays unknown.')+'<div class="lab-grid">'+rows.slice(0,limit).map(r=>gameCard(r,`${tag(r.status)}<p>${esc(r.source)} · observed ${esc(date(r.observed_at))}</p><p>Roof ${esc(r.roof)} · wind ${num(r.wind_mph)} mph · gusts ${num(r.gust_mph)} mph · rain ${r.precip_prob==null?'—':num(r.precip_prob)+'%'} · temperature ${num(r.temp_f)}°F</p><p>Hourly gap ${num(r.hour_gap,2)}h · published total adjustment ${signed(r.total_adjustment)}</p><p>${esc(r.note)}</p>${r.missing.length?'<p>Unavailable: '+esc(r.missing.join(', '))+'</p>':''}`)).join('')+'</div>'+more(rows.length);
  }
  function health(){
    const rows=(data.diagnostics||[]).filter(r=>filters().sport==='all'||r.sport===filters().sport||r.sport==='props'&&filters().sport==='nfl');
    return title('PASS IS DIFFERENT FROM AN OUTAGE','Why a board is quiet.','Freshness and coverage are measured separately. A refresh of this page checks published files; the scheduled collector obtains new prices.')+'<div class="lab-grid">'+rows.map(r=>`<article class="lab-card"><h3>${esc(r.sport.toUpperCase())} · ${esc(r.publication)}</h3><p>${r.scheduled_games} scheduled games / ${r.market_rows} market rows / ${r.qualified} qualified.</p><p>${esc(r.empty_reason)}</p><ul>${r.reasons.map(x=>'<li>'+x.count+' · '+esc(x.reason)+'</li>').join('')}</ul><p>${esc(r.note)}</p><p>Publication ${esc(date(r.generated_at))}</p></article>`).join('')+'</div>';
  }
  function mask(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0));}
  function ticket(){
    const out=$('#lab-ticket-result');if(!out)return;
    const legs=data.props.filter(q=>selected.has(q.id));
    if(legs.length<2){out.textContent=`${legs.length} selected. Select 2–8 legs from one book.`;return;}
    if(legs.length>8){out.textContent='Select no more than eight legs.';return;}
    if(new Set(legs.map(q=>q.book)).size>1){out.textContent='These prices come from different books. Choose one book for a ticket.';return;}
    const contracts=legs.map(q=>[q.event_id,q.player,q.market].join('|'));
    if(new Set(contracts).size!==contracts.length){out.textContent='Duplicate or contradictory markets cannot be included in one ticket.';return;}
    const groups=new Map();for(const q of legs){if(!groups.has(q.event_id))groups.set(q.event_id,[]);groups.get(q.event_id).push(q);}
    let joint=1,independent=1;for(const q of legs)independent*=q.probability.win;
    for(const rows of groups.values()){
      const masks=rows.map(q=>mask(q.hit_mask));let hits=0;
      for(let i=0;i<rows[0].simulations;i++){const bit=1<<(i%8);if(masks.every(m=>m[Math.floor(i/8)]&bit))hits++;}
      joint*=hits/rows[0].simulations;
    }
    out.textContent=`${legs.length} legs / ${groups.size} games / ${legs[0].book}. Joint win: ${pct(joint)}. Independent comparison: ${pct(independent)}. Difference: ${signed((joint-independent)*100)} percentage points. Combined book price and ticket EV are unavailable. Participation and settlement rules remain conditional.`;
  }
  function render(){if(!data)return;$('#lab-panel').innerHTML=({competition,efficiency,lineups,prices,props,validation,calibration,weather,health}[tab])();ticket();$('#lab-panel').querySelectorAll('select.lab-scenario-select').forEach(s=>s.addEventListener('change',()=>{const g=data.games.find(g=>g.event_id===s.dataset.event&&g.sport===s.dataset.sport);document.getElementById(`scenario-${g.sport}-${g.event_id}`).innerHTML=scenarioBody(g.scenarios[+s.value]);}));$('#lab-more')?.addEventListener('click',()=>{limit+=36;render();});$('#lab-clear')?.addEventListener('click',()=>{selected.clear();render();});$('.lab-panel').querySelectorAll('.lab-leg').forEach(el=>el.addEventListener('change',()=>{if(el.checked)selected.add(el.dataset.id);else selected.delete(el.dataset.id);ticket();}));}
  document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>{tab=button.dataset.tab;limit=36;document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b===button)));render();}));
  for(const selector of ['#lab-sport','#lab-book','#lab-search'])$(selector).addEventListener(selector.includes('search')?'input':'change',()=>{limit=36;render();});
  $('#lab-export').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='kevbotbets-model-lab.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
  let refreshing=null;
  function refresh(){
    if(refreshing)return refreshing;
    $('#lab-refresh').disabled=true;
    refreshing=fetch('data/research/report.json?v='+Date.now(),{cache:'no-store',signal:AbortSignal.timeout(20000)}).then(r=>{if(!r.ok)throw Error('Report unavailable');return r.json();}).then(r=>{
    if(r.schema!==1||!Number.isFinite(Date.parse(r.generated_at))||!Array.isArray(r.games)||!Array.isArray(r.props)||!Array.isArray(r.tickets)||!Array.isArray(r.lab?.models)||!Array.isArray(r.market?.groups)||!r.coverage?.nfl||!Array.isArray(r.notes)||!Array.isArray(r.sources))throw Error('Invalid report format');data=r;
    const books=[...new Set(r.market.groups.flatMap(g=>g.quotes.map(q=>q.book)))].sort();$('#lab-book').innerHTML='<option value="all">All observed books</option>';$('#lab-book').insertAdjacentHTML('beforeend',books.map(b=>`<option>${esc(b)}</option>`).join(''));
    $('#lab-status').textContent=`Snapshot generated ${date(r.generated_at)} · Original quote timestamps retained · All new models are research only`;
    $('#lab-kpis').innerHTML=[[r.lab.events,'Frozen events','First pregame captures'],[r.lab.settled_events,'Settled comparisons','Pending games excluded'],[r.coverage.nfl.efficiency_training_games,'Efficiency training games','Corrected-data replay'],[r.props.length,'Opportunity projections','Participation conditional']].map(([n,s,note])=>`<div class="lab-kpi"><b>${Number(n).toLocaleString()}</b><span>${esc(s)}</span><small>${esc(note)}</small></div>`).join('');
    $('#lab-notes').innerHTML=r.notes.map(n=>`<p>${esc(n)}</p>`).join('');$('#lab-sources').innerHTML=r.sources.filter(s=>/^https:\/\//.test(s.url)).map(s=>`<p><a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.name)} ↗</a></p>`).join('');
    document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===tab)));
    $('#lab-content').hidden=false;$('#lab-export').disabled=false;render();
  }).catch(e=>{$('#lab-status').textContent=data?'Refresh failed. Retaining the last loaded report; check its publication time.':'Model Lab report unavailable. Use Refresh view to retry.';}).finally(()=>{refreshing=null;$('#lab-refresh').disabled=false;});
    return refreshing;
  }
  $('#lab-refresh').addEventListener('click',refresh);
  window.addEventListener('online',refresh);
  document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});
  setInterval(()=>{if(!document.hidden)refresh();},300000);
  refresh();
})();
