(() => {
'use strict';
const C=KevSportsDesk,$=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const requested=new URLSearchParams(location.search).get('sport');let sport=C.leagues[requested]?requested:'nfl',games=[],serial=0;
const clock=v=>{const d=new Date(v);return Number.isFinite(d.getTime())?new Intl.DateTimeFormat('en-CA',{timeZone:'America/Toronto',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(d)+' ET':'Time unavailable';};
const resources={nfl:[['nflverse','https://nflverse.nflverse.com/','Play-by-play and reproducible football data'],['NFL Next Gen Stats','https://nextgenstats.nfl.com/','Official tracking statistics']],ncaaf:[['College football scoreboard','https://www.espn.com/college-football/scoreboard','Full schedules and game coverage'],['NCAA statistics','https://www.ncaa.com/stats/football/fbs','Official college football statistics']],mlb:[['Baseball Savant','https://baseballsavant.mlb.com/','Statcast, pitch quality and contact data'],['FanGraphs','https://www.fangraphs.com/','Team, hitter and pitcher research']],nhl:[['NHL stats','https://www.nhl.com/stats/','Official team and player statistics'],['MoneyPuck data','https://moneypuck.com/data.htm','Expected goals research; source usage terms apply'],['Data Punk Hockey','https://www.datapunkhockey.com/free-data-sources/','Guide to hockey data sources']],nba:[['NBA stats','https://www.nba.com/stats','Official team and player statistics']],ncaab:[['Bart Torvik','https://barttorvik.com/','Tempo-free college basketball research'],['NCAA statistics','https://www.ncaa.com/stats/basketball-men/d1','Official Division I statistics']],wnba:[['WNBA stats','https://stats.wnba.com/','Official team and player statistics']]};
async function get(url){const response=await fetch(url,{cache:'no-store',signal:AbortSignal.timeout(12000)});if(!response.ok)throw Error('Feed unavailable');return response.json();}
function renderGames(){const query=$('#desk-search').value.trim().toLowerCase(),rows=games.filter(g=>(g.away.name+' '+g.home.name+' '+g.away.abbr+' '+g.home.abbr).toLowerCase().includes(query));$('#desk-count').textContent=rows.length+' matchups';
 const team=(t,state)=>`<div class="desk-team">${t.logo?`<img src="${esc(t.logo)}" alt="" loading="lazy">`:`<span class="team-fallback">${esc(t.abbr)}</span>`}<div><strong>${t.rank?'#'+t.rank+' ':''}${esc(t.abbr)}</strong><small>${esc(t.name)}${t.record?' · '+esc(t.record):''}</small></div><b>${state==='pre'?'—':esc(t.score??'—')}</b></div>`;
 $('#desk-games').innerHTML=rows.map(g=>`<article class="score-card" data-state="${esc(g.state)}"><header><b>${esc(g.status)}</b><span>${esc(clock(g.date))}</span></header>${team(g.away,g.state)}${team(g.home,g.state)}<p class="desk-game-note">${esc([g.venue,g.broadcast].filter(Boolean).join(' · '))}</p>${g.away.stats.length||g.home.stats.length?`<div class="desk-stats">${g.away.stats.map(s=>{const h=g.home.stats.find(x=>x.name===s.name);return `<div><span>${esc(s.value??'—')}</span><span>${esc(s.name)}</span><span>${esc(h?.value??'—')}</span></div>`;}).join('')}</div>`:''}${g.away.leader||g.home.leader?`<p class="desk-game-note">${esc([g.away.leader,g.home.leader].filter(Boolean).join(' / '))}</p>`:''}${g.url?`<a class="text-link" href="${esc(g.url)}" target="_blank" rel="noopener">ESPN game center ↗</a>`:''}</article>`).join('')||`<div class="desk-empty"><h3>${query?'No matching teams.':'No games to display.'}</h3><p>${query?'Try a team name or abbreviation.':'Choose another date. The status above shows whether the feed was successfully checked.'}</p></div>`;
 $('#desk-games').querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{const el=document.createElement('span');el.className='team-fallback';el.textContent='KB';img.replaceWith(el);},{once:true}));
}
async function fallback(key,date){
 if(!C.leagues[key].lab)return null;
 const folder=key==='mlb'?'mlb-edge':key+'-edge-lab',url=key==='mlb'?`../${folder}/data/slate-${date}.json`:`../${folder}/data/games.json`;
 const [d,m]=await Promise.all([get(url),get('../'+folder+'/data/'+(key==='mlb'?'index':'meta')+'.json')]);
 const rows=(Array.isArray(d)?d:d.games||[]).filter(g=>C.day(g.start||g.tipoff||g.date)===date);
 const side=(g,s)=>{const x=typeof g[s]==='object'?g[s]:{};return {abbr:x.abbr||g[s]||'TBD',name:x.name||g[s+'_name']||g[s]||'TBD',logo:C.safeUrl(x.logo||g[s+'_logo']),record:x.records?.overall||g[s+'_record'],score:x.score??g[s+'_score']??null,stats:[],leader:null};};
 return {stamp:d.generated_at||m.generated_at||m.updated_at,rows:rows.map(g=>({id:g.game_id||g.gamePk,date:g.start||g.tipoff||g.date,state:g.completed||g.abstract==='Final'?'post':g.state==='in'||g.status==='in'?'in':'pre',status:g.status_detail||g.status||'Published snapshot',away:side(g,'away'),home:side(g,'home'),venue:g.venue,broadcast:g.broadcast,url:C.safeUrl(g.source_url)}))};
}
function renderStandings(data){const groups=C.standings(data),wanted=['wins','losses','winPercent','points','gamesBehind','streak','pointDifferential'];
 const entries=groups.flatMap(g=>g.entries.map(e=>({...e,group:g.label}))),stats=wanted.filter(k=>entries.some(e=>e.stats?.some(s=>s.name===k))).slice(0,5);
 $('#desk-standings-head').innerHTML='<tr><th>Team</th>'+stats.map(k=>`<th>${esc(entries.flatMap(e=>e.stats||[]).find(s=>s.name===k)?.abbreviation||k)}</th>`).join('')+'</tr>';
 $('#desk-standings').innerHTML=entries.slice(0,400).map(e=>`<tr><td><b>${esc(e.team?.displayName||e.team?.abbreviation||'TBD')}</b><small>${esc(e.group)}</small></td>${stats.map(k=>`<td>${esc(e.stats?.find(s=>s.name===k)?.displayValue??'—')}</td>`).join('')}</tr>`).join('');
 $('#desk-standings-status').textContent=entries.length?`ESPN · ${data.seasonDisplayName||data.season?.year||(typeof data.season==='number'?data.season:'Current available season')} · retrieved ${clock(new Date())}.`:'No standings were supplied for the current available season.';
}
async function refresh(){const run=++serial,key=sport,league=C.leagues[key],date=$('#desk-date').value;if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return;
 $('#desk-refresh').disabled=true;$('#desk-status').textContent='Checking '+league.name+' public feeds…';games=[];renderGames();$('#desk-news').innerHTML='';$('#desk-standings').innerHTML='';$('#desk-standings-head').innerHTML='';$('#desk-news-status').textContent='Loading headlines…';$('#desk-standings-status').textContent='Loading standings…';
 const base='https://site.api.espn.com/apis/site/v2/sports/'+league.path;
 const results=await Promise.allSettled([get(base+'/scoreboard?dates='+date.replaceAll('-','')+'&limit=1000'+(key==='ncaab'?'&groups=50':key==='ncaaf'?'&groups=80':'')),get(base+'/news?limit=6'),get('https://site.api.espn.com/apis/v2/sports/'+league.path+'/standings')]);
 if(run!==serial)return;
 if(results[0].status==='fulfilled'){games=C.events(results[0].value).filter(g=>C.day(g.date)===date);$('#desk-status').textContent=`${league.name} · ESPN scoreboard retrieved ${clock(new Date())} · ${games.length} games for ${date}.`;}else{let cached=null;try{cached=await fallback(key,date);}catch{}if(run!==serial)return;games=cached?.rows||[];$('#desk-status').textContent=cached?`ESPN live request unavailable · showing published ${league.name} snapshots from ${cached.stamp?clock(cached.stamp):'an unknown collection time'}. Scores may be stale.`:`${league.name} scoreboard unavailable. No games or scores are inferred. Try Refresh desk or open the research links.`;}
 renderGames();
 if(results[1].status==='fulfilled'){const articles=(results[1].value.articles||[]).filter(a=>a.headline&&C.safeUrl(a.links?.web?.href));$('#desk-news').innerHTML=articles.slice(0,6).map(a=>`<li><a href="${esc(C.safeUrl(a.links.web.href))}" target="_blank" rel="noopener">${esc(a.headline)}</a><small>ESPN · ${esc(clock(a.published))}</small></li>`).join('');$('#desk-news-status').textContent=articles.length?'Latest available ESPN headlines.':'No headlines supplied.';}else $('#desk-news-status').textContent='Headlines are temporarily unavailable.';
 if(results[2].status==='fulfilled')renderStandings(results[2].value);else $('#desk-standings-status').textContent='Standings feed unavailable. No ranks or records are inferred.';
 $('#desk-refresh').disabled=false;
}
function select(key){sport=key;const l=C.leagues[key];document.documentElement.dataset.kbLeague=key;document.documentElement.style.setProperty('--kb-art',`url('assets/sports/${l.art}.svg')`);$('#desk-title').innerHTML=l.title;$('#desk-code').textContent=l.code;$('#desk-eyebrow').textContent=l.name+' / THE MATCHDAY DESK';$('#desk-description').textContent=l.lab?'Scores, schedules, team records and the stories behind the matchups.':'Scores, schedules and team research. Forecast and ticket qualification opens after model validation.';
 $('#desk-leagues').innerHTML=Object.entries(C.leagues).map(([k,v])=>`<button data-sport="${k}" aria-pressed="${k===key}">${v.name}</button>`).join('');$('#desk-leagues').querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>select(b.dataset.sport)));const nav=$('#desk-leagues'),active=nav.querySelector('[aria-pressed=true]');nav.scrollLeft=active.offsetLeft-nav.offsetLeft-(nav.clientWidth-active.clientWidth)/2;
 $('#desk-links').innerHTML=(l.lab?`<a href="./#${key}" target="_top">OPEN ${l.name} LAB ↗</a>`:'<a href="./#accuracy" target="_top">MODEL READINESS ↗</a>')+'<a href="./#today" target="_top">DAILY PICKS ↗</a>';
 $('#desk-sources').innerHTML=resources[key].map(([name,url,note])=>`<a href="${url}" target="_blank" rel="noopener">${name} ↗<small>${note}</small></a>`).join('');history.replaceState(null,'','?sport='+key);refresh();}
$('#desk-date').value=C.day(new Date());$('#desk-date').addEventListener('change',refresh);$('#desk-refresh').addEventListener('click',refresh);$('#desk-search').addEventListener('input',renderGames);for(const [id,delta] of [['desk-prev',-1],['desk-next',1]])$('#'+id).addEventListener('click',()=>{const d=new Date($('#desk-date').value+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+delta);$('#desk-date').value=d.toISOString().slice(0,10);refresh();});select(sport);
})();
