import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),Q=require('../site/quote-integrity.js'),S=require('../site/sync-adapter.js');
const now=Date.parse('2026-09-23T12:00:00Z');
const leg={event_id:'401',player:'Test Player',market:'Receptions',side:'over',line:4.5,model_prob:.6,start_time:'2026-09-25T00:15:00Z',price_american:-110,price_source:'model'};
const quote={...leg,price:200,book:'Book',observed_at:'2026-09-23T11:00:00Z'};
assert.ok(Q.valid(quote,leg,now));
for(const changes of [{event_id:'402'},{observed_at:'2026-09-22T11:00:00Z'},{observed_at:'2026-09-23T13:00:00Z'},{observed_at:'2026-09-23T11:00:00'},{book:''},{price:99},{price:0},{line:5.5}])assert.equal(Q.valid({...quote,...changes},leg,now),false);
assert.equal(Q.apply(leg,{[Q.key(leg)]:{price:200,book:'legacy'}},now),leg,'old unscoped imports never become real quotes');
const legs=[leg,{...leg,event_id:'402'},{...leg,event_id:'403'}];
const imported=Object.fromEntries(legs.map(l=>[Q.key(l),{...quote,event_id:l.event_id}]));
const ticket=Q.ticket({legs},imported,now);
assert.equal(ticket.american,2600);assert.equal(ticket.payout,270);assert.equal(ticket.decimal,27);
assert.ok(Math.abs(ticket.probability-.216)<1e-10);assert.equal(ticket.ev,null);
assert.equal(Q.ticket({legs:[leg,leg]},imported,now).probability,null,'same-game chance is not fabricated');
assert.equal(Q.day('2026-09-25T00:15:00Z'),'2026-09-24','late Thursday ET is not Friday');
const header='event_id,player,market,line,over_odds,book,observed_at\n';
assert.deepEqual(Q.parseCsv(header+'401,Test Player,Receptions,4.5,,Book,2026-09-23T11:00:00Z',legs,now),{});
assert.equal(Object.keys(Q.parseCsv(header+'401,Test Player,Receptions,4.5,200,Book,2026-09-23T11:00:00Z',legs,now)).length,1);
const entry={id:'bet-a',title:'My real bet',price_american:-110,stake:7.5,result:'Win',note:'Accepted before kickoff',book:'Book',added_at:'2026-09-23T12:00:00Z',kind:'parlay',legs:['one','two'],custom:'retain',confirmed_actual:true};
const native=S.fromCanonical(S.toCanonical(entry));
for(const k of Object.keys(entry))assert.deepEqual(native[k],entry[k],k);
assert.equal(S.fromCanonical({...S.toCanonical(entry),stake:9,notes:'Updated in HQ'}).stake,9);
assert.equal(S.fromCanonical({...S.toCanonical(entry),stake:9,notes:'Updated in HQ'}).note,'Updated in HQ');
console.log('Quote, ticket, Eastern date and shared-ledger regression checks passed');
