import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),C=require('../site/parlay-history-core.js');
const start='2026-10-01T18:00:00Z',graded='2026-10-01T22:00:00Z',now=Date.parse('2026-10-02T12:00:00Z');
const legs=[1,2].map(n=>({event_id:String(n),player:'Player '+n,team:'Team',market:'Receiving yards',side:'over',line:50.5,start_time:start,pick:'Over 50.5'}));
const snapshot=C.snapshot({id:'one',scope:'slate'},legs,'2026-10-01T12:00:00Z');
legs[0].line=99;assert.equal(snapshot.legs[0].line,50.5);
const results=snapshot.legs.map(l=>({...l,result:'Win',actual:60,graded_at:graded}));
assert.equal(C.settle(snapshot,results,now).result,'Win');
assert.equal(C.settle(snapshot,results.slice(0,1),now).result,'Pending');
assert.equal(C.settle(snapshot,[{...results[0],result:'Loss'},results[1]],now).result,'Loss');
assert.equal(C.settle(snapshot,[{...results[0],result:'Push'},results[1]],now).result,'Review');
assert.equal(C.settle(snapshot,[{...results[0],result:'Void'},results[1]],now).result,'Review');
assert.equal(C.settle(snapshot,[...results,{...results[0],result:'Loss'}],now).result,'Review');
assert.equal(C.settle(snapshot,results.map(r=>({...r,event_id:'wrong'})),now).result,'Pending');
assert.equal(C.settle(snapshot,results.map(r=>({...r,team:'Other'})),now).result,'Pending');
assert.equal(C.settle(snapshot,results.map(r=>({...r,line:49.5})),now).result,'Pending');
assert.equal(C.settle(snapshot,results.map(r=>({...r,graded_at:'2026-12-01T22:00:00Z'})),now).result,'Pending');
assert.equal(C.settle(snapshot,results.map(r=>({...r,actual:null})),now).result,'Pending');
assert.throws(()=>C.snapshot({},[legs[0],legs[0]]),/Duplicate/);
const entry={id:'bet',kind:'parlay',parlay_snapshot:snapshot,result:'Pending',stake:10,price_american:500};
const saved=C.settleEntries([entry],results,now);assert.equal(saved.entries[0].result,'Win');assert.equal(entry.result,'Pending');
assert.equal(saved.entries[0].price_american,500);assert.equal(saved.entries[0].stake,10);
assert.equal(C.settleEntries(saved.entries,results,now).changed,false);
assert.equal(C.settleEntries([{...entry,settlement_mode:'manual'}],results,now).changed,false);
assert.equal(C.settleEntries([{...entry,parlay_snapshot:null}],results,now).changed,false);
assert.equal(C.settleEntries([entry],[{...results[0],result:'Loss'}],now).entries[0].result,'Pending');
assert.equal(C.settleEntries([entry],results.map(r=>({...r,result:'Void'})),now).entries[0].result,'Pending');
console.log('Parlay snapshots, exact identities, W/L, void review, manual overrides and idempotent settlement passed.');
