import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),T=require('../ticket-core.js'),D=require('../ledger-details.js');
const r={key:'nfl',eventId:'1',start:'2026-09-15T20:00Z',market:'ATS',side:'away',line:7,price:-110,book:'DraftKings'};
const game={id:'1',completed:true,home:24,away:20};
assert.equal(T.gradeScore(r,game),'Win');assert.equal(T.gradeScore({...r,line:4},game),'Push');assert.equal(T.gradeScore({...r,line:3},game),'Loss');
assert.equal(T.gradeScore(r,{...game,completed:false}),null);assert.equal(T.gradeScore(r,{...game,id:'2'}),null);assert.equal(T.gradeScore(r,{...game,home:null}),null);
assert.equal(T.gradeScore({...r,market:'TOTAL',side:'under',line:44},game),'Push');assert.equal(T.gradeScore({...r,market:'TOTAL',side:'under',line:43.5},game),'Loss');
assert.equal(T.gradeScore({...r,market:'ML',side:'away',line:null},game),'Loss');assert.equal(T.gradeScore({...r,side:'unknown'},game),null);
assert.notEqual(T.outcomeKey(r),T.outcomeKey({...r,line:3}));assert.equal(T.selectionKey(r),T.selectionKey({...r,line:3}));
assert.equal(T.closing(r,{...r,line:6,price:-105,quote:'2026-09-15T19:50Z'}).line_advantage,1);
assert.equal(T.closing(r,{...r,line:6,price:-105,quote:'2026-09-15T19:50Z'}).price_advantage,null);
assert.equal(T.closing(r,{...r,book:'Other',quote:'2026-09-15T19:50Z'}),null);assert.equal(T.closing(r,{...r,quote:'2026-09-15T20:01Z'}),null);
assert.equal(T.profit('Pending',-110),null);assert.equal(T.profit('Win',150),1.5);assert.equal(T.profit('Loss',150),-1);
const summary={header:{id:'1',competitions:[{status:{type:{completed:true}}}]},boxscore:{players:[{statistics:[{name:'passing',keys:['completions/passingAttempts'],athletes:[{athlete:{id:'42',displayName:'Bo Nix'},stats:['22/35']}]}]}]}};
const prop={...r,player:'Bo Nix',market:'Pass attempts',side:'over',line:33.5};
assert.equal(T.gradeProp(prop,summary),'Win');assert.equal(T.gradeProp({...prop,player:'Unknown'},summary),null);assert.equal(T.gradeProp({...prop,market:'Anytime touchdown'},summary),null);
const perf=T.performance([{pick:r,published_at:'1',result:{status:'Win'}},{pick:{...r,line:3,price:200},published_at:'2',result:{status:'Loss'}},{pick:{...r,eventId:'2'},published_at:'1',result:{status:'Push'}}]);
assert.equal(perf[0].picks,2);assert.equal(perf[0].wins,1);assert.equal(perf[0].risked,2);assert.equal(perf[0].roi,(100/110)/2);
assert.equal(D.observe([],[{id:'1',stake:10}],'now','a').length,0);
const changes=D.observe([{id:'1',stake:10,status:'Pending'}],[{id:'1',stake:12,status:'Win',device:'phone',updated_at:'server'}],'now','desktop');
assert.equal(changes[0].device,'phone');assert.equal(changes[0].changes.length,2);
const settings={...D.historySetting(changes[0],'one'),...D.historySetting(changes[0],'two')};assert.equal(D.history(settings).length,2);
assert.equal(D.closing({},'1'),null);
console.log('Ticket grading, line normalization, price comparison, deduplication and ledger history checks passed.');
