import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
const root=path.resolve('../../_site'),server=createServer(async(req,res)=>{let f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(req.url.endsWith('/'))f=path.join(f,'index.html');try{res.setHeader('Content-Type',({'.js':'application/javascript','.css':'text/css','.json':'application/json'})[path.extname(f)]||'text/html');res.end(await readFile(f));}catch{res.writeHead(404).end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true});
const stamp='2026-10-10T14:00:00Z',now=Date.parse(stamp),start='2026-10-11T17:00:00Z';
const retained={sport:'NFL',event_id:'401',player:'Fixture Player',market:'Receptions',side:'over',line:4.5,price_american:110,price_decimal:2.1,book:'DraftKings',pick:'Fixture Player over 4.5 Receptions',model_prob:.65,model_prob_no_push:.65,push_prob:0,start_time:start,updated_at:'2026-10-10T13:00:00Z',quote_status:'retained',tier:'PASS',reason:'Retained quote during a feed outage; confirm a current sportsbook price',held:true,samples:8};
const meta={generated_at:stamp,price_source_status:'retained',counts:{priced_quotes:1,projections:2,book_priced_legs:1},source_by_sport:{NFL:{source:'Public recovery',errors:['Feed temporarily empty']}},quote_health:{observed:0,retained:1,expired:2,max_age_hours:4,board_reasons:{'retained / confirmation':1},sources:{Covers:{status:'unavailable',quotes:0,error:'No matchable offers'},Fallback:{status:'reference',quotes:1}},markets:{Receptions:{projections:2,observed:0,retained:1,reference:0,expired:2,qualified:0},'Passing yards':{projections:2,observed:0,retained:0,reference:0,expired:0,qualified:0}}}};
try{for(const width of [1440,393]){
 const context=await browser.newContext({viewport:{width,height:1000},serviceWorkers:'block',timezoneId:'America/Toronto'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install({time:now});
 await context.route('https://**/*',route=>route.abort());
 await page.route('**/props-edge/data/*.json*',route=>{const file=new URL(route.request().url()).pathname.split('/').pop(),values={'meta.json':meta,'legs.json':[{...retained,id:'fixture',price_source:'book'}],'parlays.json':{tickets:[],targets:[]},'board.json':[retained],'projections.json':[],'accuracy-summary.json':{},'accuracy.json':{},'parlay-results.json':{schema:1,records:[]},'parlay-history.json':{tickets:[]}};return route.fulfill({contentType:'application/json',body:JSON.stringify(values[file]||[])});});
 await page.goto(origin+'/props-edge/',{waitUntil:'networkidle'});await page.locator('[data-tab="best"]').click();await page.locator('#stake-system').waitFor();assert.equal(await page.locator('[data-qualified-bet]').count(),0);assert.match(await page.locator('#restored-best').innerText(),/retained/i);
 await page.locator('[data-tab="sources"]').click();await page.getByText('Price coverage and recovery',{exact:true}).waitFor();const text=await page.locator('#restored-sources').innerText();assert.match(text,/Retained offers keep their original source time/);assert.match(text,/Feed outage; current book confirmation needed/);assert.match(text,/No verified market price/);assert.match(text,/Covers.*unavailable/);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await page.locator('[data-tab="best"]').click();await page.getByText(/All priced market watches/).click();assert.match(await page.locator('#restored-best').innerText(),/13:00|9:00/);assert.match(await page.locator('#restored-best').innerText(),/Retained quote during a feed outage/);assert.equal(await page.locator('[data-qualified-bet]').count(),0);
 await mkdir('test-results/prop-recovery',{recursive:true});await page.screenshot({path:`test-results/prop-recovery/coverage-${width}.png`,fullPage:true});assert.deepEqual(errors,[]);await context.close();console.log(`Prop outage retention, source diagnostics, expired coverage and no automatic bets passed at ${width}px`);
}}finally{await browser.close();await new Promise(r=>server.close(r));}
