import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),R=require('../ledger-recovery.js'),H=require('../pick-history.js');
const row={id:'props:one',app:'props',selection:'Example Over 15.5',stake:5,price:-110,status:'Pending',native:{player:'Example',token:'DO-NOT-EXPORT',nested:{apiKey:'PRIVATE',market:'yards'}}};
const raw=JSON.stringify(row),backup=R.create([row],'scope','2026-09-16T12:00:00Z');
assert.equal(JSON.stringify(row),raw);assert.ok(!JSON.stringify(backup).includes('DO-NOT-EXPORT'));assert.ok(!JSON.stringify(backup).includes('PRIVATE'));assert.equal(backup.rows[0].native.player,'Example');
assert.throws(()=>R.validate(backup,'different'),/same sheet/);
assert.throws(()=>R.create([row,row],'scope','2026-09-16'),/duplicate/);
assert.throws(()=>R.create([{...row,status:'Winner'}],'scope','2026-09-16'),/invalid result/);
assert.throws(()=>R.create([{...row,stake:'invalid'}],'scope','2026-09-16'),/numeric/);
assert.throws(()=>R.create([{...row,stake:-1}],'scope','2026-09-16'),/negative/);
assert.equal(R.plan(backup,[]).missing[0].base_rev,R.FENCE);
assert.equal(R.plan(backup,[{...row,status:'Win'}]).missing.length,0);
assert.equal(R.plan(backup,[{...row,deleted:true}]).deleted.length,1);
assert.equal(R.plan(R.create([{...row,deleted:true}],'scope','2026-09-16'),[]).missing.length,0);
const storage={value:null,getItem(){return this.value;},setItem(k,v){this.value=v;}};
R.remember(storage,'key',backup);R.remember(storage,'key',R.create([row],'scope','2026-09-16T13:00:00Z'));assert.equal(JSON.parse(storage.value).length,1);
for(let i=0;i<15;i++)R.remember(storage,'key',R.create([{...row,stake:i}],'scope',`2026-09-16T14:${String(i).padStart(2,'0')}:00Z`));assert.equal(JSON.parse(storage.value).length,10);
const limited={getItem:()=>storage.value,setItem(k,v){if(JSON.parse(v).length>2)throw Error('quota');this.value=v;}};R.remember(limited,'key',backup);assert.equal(JSON.parse(limited.value).length,2);
const stamp='2026-09-16T12:00:00Z',later='2026-09-16T12:30:00Z';
const play={game_id:'1',tipoff:'2026-09-17T20:00:00Z',odds_fetched_at:stamp,market:'ATS',side:'home',tier:'GOOD',stake:5,price:-110,line:-3.5,pick:'HOME -3.5',matchup:'AWAY @ HOME',book:'Book',edge:.03};
const bundle={meta:{generated_at:stamp},board:[play]};
const baseline=H.observe(null,{nfl:bundle},stamp);assert.equal(baseline.events.length,0);
let next=H.observe(baseline,{nfl:{meta:{generated_at:later},board:[{...play,price:-120,line:-4.5,pick:'HOME -4.5',tier:'LEAN'}]}},later);
assert.deepEqual(next.events[0].changes.map(x=>x.field),['price','line','tier']);
assert.equal(H.observe(next,{nfl:{meta:{generated_at:later},board:[{...play,price:100}]}},later).events.length,next.events.length);
assert.equal(H.observe(baseline,{nfl:{...bundle,error:true,board:[]}},later).events.length,0);
assert.equal(H.observe(baseline,{nfl:{meta:{generated_at:later,price_source_status:'unavailable'},board:[]}},later).events.length,0);
assert.equal(H.observe(baseline,{nfl:{meta:{generated_at:later},board:[]}},later).events[0].changes[0].field,'qualified list');
assert.equal(baseline.events.length,0);assert.equal(bundle.board[0].price,-110);
console.log('Backup validation, scope, redaction, retention, safe recovery and forward-only pick history passed');
