import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
const root=path.resolve('../../_site'),server=createServer(async(req,res)=>{let f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(req.url.endsWith('/'))f=path.join(f,'index.html');try{res.setHeader('Content-Type',({'.js':'application/javascript','.css':'text/css','.json':'application/json'})[path.extname(f)]||'text/html');res.end(await readFile(f));}catch{res.writeHead(404).end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true}),stamp='2026-10-10T15:00:00Z';
const control={sport:'nfl',market:'ATS',baseline_version:'current-v1',status:'paused',recommendations_paused:true,reasons:['Model error exceeds market'],contracts:220,events:120,days:35,market_pairs:210,predicted:.6,actual:.5,shadow_status:'shadow-only',shadow_tests:60};
const meta={generated_at:stamp,model_version:'current-v1',calendar:[{season_type:2,week:5,label:'Week 5',start:'2026-10-07T07:00Z',end:'2026-10-14T06:59Z'}],validation:{markets:[control]}};
const games=[{game_id:'1',week:5,home:'Home',away:'Away',date:'2026-10-11T17:00Z',projection:{mu:.5},odds:{spread_home:-3,spread_price_home:-115,spread_price_away:105,book:'Book'}},{game_id:'2',week:5,home:'Second Home',away:'Second Away',date:'2026-10-11T20:00Z',projection:{mu:2}}];
try{for(const width of [1440,393]){
 let feedFailure=false;const context=await browser.newContext({viewport:{width,height:1000},serviceWorkers:'block',timezoneId:'America/Toronto'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install({time:Date.parse(stamp)});await context.route('https://**/*',r=>r.abort());
 await page.route('**/*-edge-lab/data/*.json*',route=>{const url=new URL(route.request().url()),n=url.pathname.split('/').pop(),nfl=url.pathname.includes('/nfl-edge-lab/');if(feedFailure&&nfl)return route.fulfill({status:503,body:'unavailable'});return route.fulfill({contentType:'application/json',body:JSON.stringify(n==='meta.json'?meta:n==='games.json'&&nfl?games:n==='board.json'&&nfl?[{game_id:'1',market:'ATS',side:'away',tier:'PASS',validation_policy:{paused:true}}]:[])});});
 await page.goto(origin+'/bet-ledger-hq/all-spreads.html',{waitUntil:'networkidle'});await page.locator('.spread-row').first().waitFor();assert.equal(await page.locator('.spread-row').count(),2);assert.match(await page.locator('#games').innerText(),/One game option/);assert.match(await page.locator('#games').innerText(),/recommendations paused/);
 const first=page.locator('.spread-row').first();await first.locator('[data-side=away]').click();await first.locator('form button').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('kevbot-all-spreads-v1')||'{}')['nfl:1']);const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('kevbot-all-spreads-v1'))['nfl:1']);assert.equal(saved.tier,'MANUAL');assert.equal(saved.line,3);assert.equal(saved.forecast_rating,'AVOID');
 const second=page.locator('.spread-row').nth(1);await second.locator('[name=line]').fill('-2.5');await second.locator('[name=price]').fill('-110');await second.locator('[name=book]').fill('My Book');await second.locator('form button').click();await page.waitForFunction(()=>Object.keys(JSON.parse(localStorage.getItem('kevbot-all-spreads-v1')||'{}')).length===2);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 feedFailure=true;await page.locator('#refresh').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('retained schedule'));assert.equal(await page.locator('.spread-row').count(),2);assert.equal(await page.locator('.spread-row form button:disabled').count(),0);
 const performance=JSON.parse(await readFile(path.join(root,'bet-ledger-hq/data/performance.json'),'utf8'));performance.validation={markets:[control]};await page.route('**/bet-ledger-hq/data/performance.json*',r=>r.fulfill({contentType:'application/json',body:JSON.stringify(performance)}));await page.goto(origin+'/bet-ledger-hq/accuracy.html',{waitUntil:'networkidle'});await page.getByText('Confidence has to earn trust.',{exact:true}).waitFor();assert.match(await page.locator('#perf-validation').innerText(),/paused/);assert.match(await page.locator('#perf-validation').innerText(),/Research remains available/);assert.match(await page.locator('#perf-validation').innerText(),/Automatic promotion stays off/);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await mkdir('test-results/validation-options',{recursive:true});await page.screenshot({path:`test-results/validation-options/performance-${width}.png`,fullPage:true});
 const legs=[1,2].map(i=>({id:'fixture-'+i,event_id:'fixture-game',player:'Player '+i,market:'Receptions',side:'over',line:1.5,pick:'Player '+i+' over 1.5 Receptions',price_source:'book',price_american:150,price_decimal:2.5,model_prob:.6,book:'Fixture Book',matchup:'A @ B',start_time:'2026-10-11T17:00:00Z',updated_at:stamp,tier:'PASS',held:true}));
 await page.route('**/props-edge/data/parlays.json*',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({generated_at:stamp,targets:[500,50000],profiles:{longshot:{targets:[500,50000]},core:{targets:[200,500,1000]}},tickets:[{id:'fixture-500',scope:'game',profile:'longshot',label:'A @ B',target:500,leg_count:2,legs,games:['A @ B'],price_american:525,price_decimal:6.25,estimated_prices:false,same_game:true,independent_prob:.36,model_prob:null,start_time:'2026-10-11T17:00:00Z',actionable:false,status:'research'}]})}));
 await page.goto(origin+'/props-edge/#parlays',{waitUntil:'networkidle'});await page.locator('.target[data-target="500"]').waitFor();assert.equal(await page.locator('#parlay-profile').inputValue(),'longshot');assert.equal(await page.locator('.target[data-target="50000"]').count(),1);await page.locator('.target[data-target="500"]').click();await page.locator('[data-scope="game"]').click();await page.locator('#parlays .ticket').first().waitFor();assert.match(await page.locator('#parlays').innerText(),/RESEARCH/);assert.match(await page.locator('#parlays').innerText(),/Combined price needs confirmation/);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:`test-results/validation-options/moonshots-${width}.png`,fullPage:true});assert.deepEqual(errors,[]);await context.close();console.log(`Paused market controls, every-game manual choices and missing-price entry passed at ${width}px`);
}}finally{await browser.close();await new Promise(r=>server.close(r));}
