import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),P=require('../price-core.js'),X=require('../execution-core.js'),E=require('../evidence-core.js'),C=require('../today-core.js'),A=require('../alerts-core.js');
const at='2026-10-10T18:00:00Z',now=Date.parse(at),start='2026-10-10T19:00:00Z';
const pick={key:'nfl',eventId:'1',start,market:'ATS',side:'away',line:3.5,pick:'A +3.5',book:'Book A',price:-110,quote:at,worst:-115,event:'A @ B'};
const other={...pick,book:'Book B',price:105};
assert.equal(P.compare(pick,[pick,other,{...other,line:4},{...other,eventId:'2'},{...other,side:'home'},{...other,start:'2026-10-11T19:00:00Z'},{...other,key:'ncaaf'}],now).best.price,105);
assert.equal(P.compare(pick,[{...other,quote:null},{...other,quote:'2026-10-10T12:00:00Z'},{...other,quote:'2026-10-10T18:01:00Z'}],now).coverage,0);
assert.equal(P.compare(pick,[other,{...other,price:-125,quote:'2026-10-10T18:01:00Z'}],now+60000).best.price,-125,'newest quote beats obsolete better price');
const archive=P.observe(null,[pick],at);assert.deepEqual(P.observe(archive,[],at).last,archive.last);assert.deepEqual(P.observe(archive,[{...pick,price:120,quote:'2026-10-10T20:00:00Z'}],'2026-10-10T20:00:00Z').last,archive.last,'post-start quotes cannot overwrite last pregame');
const baseline=A.scan(null,{tracked:[pick],quotes:[pick]},at);const lost={...pick,price:-125};
const alert=A.scan(baseline.state,{tracked:[pick],quotes:[lost]},at);assert.equal(alert.events.filter(e=>e.kind==='price-limit').length,1);assert.equal(A.scan(alert.state,{tracked:[pick],quotes:[lost]},at).events.length,0);assert.equal(A.scan(alert.state,{tracked:[pick],quotes:[pick]},at).events.filter(e=>e.kind==='price-limit').length,1);
assert.equal(P.crossing(pick,pick,{...lost,line:4}),null);
const board={game_id:'1',game_date:start,market:'ATS',side:'away',line:-3.5,price:-110,book:'Book A',odds_observed_at:at,stake:0,tier:'PASS',held:true,model_prob:.55,value_policy:{}};
assert.equal(C.plays('nfl',{meta:{generated_at:at},board:[board]},now).length,0);assert.equal(C.plays('nfl',{meta:{generated_at:at},board:[board]},now,{quotes:true})[0].line,3.5);
const row={id:'nfl:1',app:'nfl-lab',sport:'NFL',event:'A @ B',event_date:'2026-10-10',selection:'A +3.5',market:'ATS',side:'away',line:-3.5,price:-110,book:'Book A',native:{game_date:start}};
const receipt=X.confirm(row,{book:'Book A',price:-110,line:3.5,stake:10,placed_at:'2026-10-10T17:00:00Z',status:'Win'},null,at);
const input={book:'Book A',price:-125,line:3.5,observed_at:at,same_contract:true};const close=X.confirmClose(row,receipt,input,at);
assert.ok(X.closeComparison(receipt,close).movement>0);assert.equal(X.closeComparison(receipt,close).minutes,60);
for(const patch of [{line:-3.5},{book:'Book B'},{same_contract:false},{observed_at:start},{observed_at:'2026-10-10T16:00:00Z'},{observed_at:'2026-10-10T18:01:00Z'},{price:50}])assert.throws(()=>X.confirmClose(row,receipt,{...input,...patch},at));
assert.equal(X.closeComparison({...receipt,accepted:{...receipt.accepted,price:100}},close).comparable,false);
assert.equal(X.closeComparison(receipt,{price:-125,line:3.5}).comparable,false,'legacy entries do not become verified receipt observations');
const settings={[X.key(row.id)]:JSON.stringify(receipt),[X.closeKey(row.id)]:JSON.stringify(close)};
const score=E.score([row,{...row,id:'unconfirmed',stake:999,status:'Win'}],settings)[0];assert.equal(score.confirmed,1);assert.equal(score.settled,1);assert.equal(score.range,null);assert.equal(score.closes,1);assert.ok(Math.abs(score.roi-100/110)<1e-9);
const many=Array.from({length:100},(_,i)=>({row:{event_date:'2026-08-'+String(i%28+1).padStart(2,'0')},receipt:{accepted:{...receipt.accepted,status:i%2?'Win':'Loss'}}}));assert.ok(E.interval(many).range);assert.equal(E.interval(many.map(e=>({...e,row:{event_date:'2026-08-01'}}))).range,null);
assert.equal(E.interval(many.map((e,i)=>({...e,row:{event_date:'2026-08-01T'+String(i%24).padStart(2,'0')+':00:00Z'}}))).days,1,'different kickoff times do not become independent dates');
assert.equal(E.interval([...many,{...many[0],row:{event_date:''}}]).range,null,'missing event dates cannot manufacture clustered uncertainty');
console.log('PASS exact-contract comparison, stale quotes, price crossings, pregame archives, receipt binding and clustered actual evidence');
