import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),W=require('../football-core.js');
const now=Date.parse('2026-09-19T12:00:00Z');
const row={price:-110,ev:.04,action_edge:.01,tier:'PASS',market:'ATS'};
assert.equal(W.candidate(row,now,.005).display_tier,'RESEARCH LEAN');
assert.equal(W.candidate(row,now,.015),null);
assert.equal(W.candidate({...row,ev:-.01},now,0),null);
assert.equal(W.candidate({...row,filtered:'odds feed integrity warning'},now,0),null);
assert.equal(W.candidate({...row,filtered:'outside the top 6 plays for this week'},now,.005).research,true);
assert.equal(W.candidate({...row,odds_observed_at:'2026-09-18T12:00:00Z'},now,0),null);
assert.equal(W.candidate({...row,held:true},now,0),null);
assert.equal(W.candidate({...row,tier:'LEAN'},now,.005).research,false);
const bundle={meta:{generated_at:'2026-09-19T11:00:00Z'},games:[{game_id:'1',date:'2026-09-20T17:00:00Z',season_type:2,home:'A',away:'B',projection:{mu:3,ratings_known:true}}],board:[{...row,game_id:'1'}]};
assert.equal(W.slate('ncaaf',bundle,'2026-09-19',now)[0].suggestions.length,1);
assert.equal(W.slate('ncaaf',bundle,'2026-09-19',now+5*3600000)[0].suggestions.length,0);
assert.equal(W.slate('ncaaf',bundle,'2026-09-21',now).length,0);
assert.equal(W.addDays('2026-12-29',7),'2027-01-05');
console.log('Weekly football: lower research threshold, data/price guards, stale-feed rejection, and date window passed');
